logging:
  level:
    com.ddd.praha.processor: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [PROCESSOR] [%thread] %-5level %logger{36} - %msg%n"

management:
  otlp:
    metrics:
      export:
        url: "http://localhost:4318/v1/metrics"
    tracing:
      endpoint: "http://localhost:4318/v1/tracing"
    logging:
      endpoint: "http://localhost:4318/v1/logs"

spring:
  application:
    name: praha-processor
  
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      creator: any
    serialization:
      write-dates-as-timestamps: false
  port: 8081