version: 2
updates:
  # Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    reviewers:
      - "ttakuma17"
    assignees:
      - "ttakuma17"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "gradle"
    allow:
      # Major version updates for all dependencies
      - dependency-type: "all"
    ignore:
      # Ignore specific dependencies that need manual review
      - dependency-name: "org.springframework.boot"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.postgresql:postgresql"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    reviewers:
      - "ttakuma17"
    assignees:
      - "ttakuma17"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"