logging:
  level:
    praha: DEBUG
#  structured:
#    format:
#      console: ecs

server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  otlp:
    metrics:
      export:
        url: "http://localhost:4318/v1/metrics"
    tracing:
      endpoint: "http://localhost:4318/v1/tracing"
    logging:
      endpoint: "http://localhost:4318/v1/logs"

spring:
  application:
    name: praha
  
  datasource:
    url: jdbc:postgresql://localhost:5432/praha
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      creator: any
    serialization:
      write-dates-as-timestamps: false
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false
    schemas: public

mybatis:
  configuration:
    map-underscore-to-camel-case: true